networks:
  campus_net:
    driver: bridge

services:
  database:
    image: postgres:15-alpine
    container_name: campuslink-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Paris
    networks:
      - campus_net
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: campuslink-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      TZ: Europe/Paris
    networks:
      - campus_net
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}  # ✅ passé au build
    container_name: campuslink-web
    restart: unless-stopped
    ports:
      - "80:80"  # ✅ Nginx écoute sur 80, pas 5173
    networks:
      - campus_net
    depends_on:
      - backend

volumes:
  pg_data: