# Définition d'un réseau privé pour nos conteneurs (Sécurité standard)
networks:
  campus_net:
    driver: bridge

services:
  # ==========================================
  # 1. BASE DE DONNÉES (PostgreSQL)
  # ==========================================
  database:
    image: postgres:15-alpine
    container_name: campuslink-db
    restart: unless-stopped
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Paris
    ports:
      - "5432:5432" 
    networks:
      - campus_net
    volumes:
      - pg_data:/var/lib/postgresql/data 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # ==========================================
  # 2. BACKEND (Node.js + Prisma)
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Utilise la version optimisée pour le développement
    container_name: campuslink-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      TZ: Europe/Paris
    networks:
      - campus_net
    depends_on:
      - database # Attendre que la DB soit prête avant de lancer l'API
      
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads  
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # ==========================================
  # 3. FRONTEND (Vue.js + Vite)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campuslink-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - campus_net
    environment:
      TZ: Europe/Paris
    depends_on:
      - backend # Attendre que l'API soit prête avant de lancer la vue
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  ai-moderation:
    image: ollama/ollama:latest
    container_name: campuslink-ai
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Pour ne pas retélécharger le modèle à chaque redémarrage
    networks:
      - campus_net
# Déclaration du volume persistant pour la base de données
volumes:
  pg_data:
  uploads_data:
  ollama_data: