name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR via Azure CLI
        run: az acr login --name acrcampuslink

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: acrcampuslink.azurecr.io/backend:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: acrcampuslink.azurecr.io/frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      # ✅ Redémarre les App Services pour prendre la nouvelle image
      - name: Restart Backend App Service
        run: az webapp restart --name  --resource-group rg-campuslink-prod

      - name: Restart Frontend App Service
        run: az webapp restart --name campuslink-backend-api --resource-group rg-campuslink-prod